### PR TITLE
SignUp Rework (Icons + Multiple Page Split)

### PR DESCRIPTION
**Pull request by bentvelj**
Issue: #109 + #112
Figma: https://www.figma.com/file/b6DxFopzG6sa2c4ke7wJm7/Olympia-Capston-UI?node-id=106%3A243&t=CFMhhlPW7YUzbXwj-0

### CODE REVIEW

**Comment by bentvelj** [comment]
I also removed the `dist` from hermes, no reason we should have build artifacts in repo

**Comment by bentvelj** [comment]
Working on splitting process into multiple pages

**Comment by bentvelj** [comment]
Alright, sign up form is in a good spot. Styling can be tweaked later. There is some repeated styling, but I think given that the password page is not quite congruent with the others, a bit repeated code is simpler than trying to generalize everything

**Comment by dimitritsampiras** [comment]
What's with all the svg additions? Why not just use Heroicon's caution icon? It would be more in theme with the rest of the app.

**Comment by dimitritsampiras** [comment]
Also, sign up should create an empty user profile as well.

**Comment by bentvelj** [comment]
> What's with all the svg additions? Why not just use Heroicon's caution icon? It would be more in theme with the rest of the app.

There is only one SVG added, merely as a placeholder for our torch icon that is to come.

> Also, sign up should create an empty user profile as well.

Right now it creates a user & pass pair, but yes.

**Comment by bentvelj** [comment]
Merging this

**Pull request merged**
